const SHOP_ACTION_TYPES = {

    GET_COLLECTIONS_START: 'GET_COLLECTIONS_START',
    GET_COLLECTIONS_SUCCESS: 'GET_COLLECTIONS_SUCCESS',
    GET_COLLECTIONS_FAILURE : 'GET_COLLECTIONS_FAILURE',

    GET_BEST_SALE_START:'GET_BEST_SALE_START',
    GET_BEST_SALE_SUCCESS: 'GET_BEST_SALE_SUCCESS',
    CHANGE_CURRENT_PAGE: 'CHANGE_CURRENT_PAGE'
}

export default SHOP_ACTION_TYPES;