const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
  DECREASE_ITEM_TO_CART: 'DECREASE_ITEM_TO_CART',
  DELETE_ITEM_TO_CART: 'DELETE_ITEM_TO_CART',
  TOGGLE_CHECKOUT_MODEL: 'TOGGLE_CHECKOUT_MODEL',
  CLEAR_CART_SIGN_OUT: 'CLEAR_CART_SIGN_OUT',
};

export default CartActionTypes;
