const CHECKOUT_ACTIONS_TYPE = {
    CHECK_OUT_START: 'CHECK_OUT_START',
    CHECK_OUT_SUCCESS: 'CHECK_OUT_SUCCESS',
    CHECK_OUT_FAILURE : 'CHECK_OUT_FAILURE',

    SET_STATE_TO_FALSE : 'SET_STATE_TO_FALSE',
    OPEN_MODEL_CHECK_OUT : 'OPEN_MODEL_CHECK_OUT',
}

export default CHECKOUT_ACTIONS_TYPE;