const BOOKING_ACTION_TYPES = {
  GET_BOOKING_START: 'GET_BOOKING_START',
  GET_BOOKING_SUCCESS: 'GET_BOOKING_SUCCESS',
  GET_BOOKING_FAILURE: 'GET_BOOKING_FAILURE',

  UPDATE_COMPLETE_START: 'UPDATE_COMPLETE_START',
  UPDATE_COMPLETE_MULTIPLE_START: 'UPDATE_COMPLETE_MULTIPLE_START',
  UPDATE_COMPLETE_SUCCESS: 'UPDATE_COMPLETE_SUCCESS',
};

export default BOOKING_ACTION_TYPES;
