const BOOKING_ACTION_TYPES = {
  GET_BOOKING_START: 'GET_BOOKING_START',
  GET_BOOKING_SUCCESS: 'GET_BOOKING_SUCCESS',
  GET_BOOKING_FAILURE: 'GET_BOOKING_FAILURE',

  GET_BOOKING_WAYBILL_START: 'GET_BOOKING_WAYBILL_START',
  GET_BOOKING_WAYBILL_SUCCESS: 'GET_BOOKING_WAYBILL_SUCCESS',
  GET_BOOKING_WAYBILL_FAILURE: 'GET_BOOKING_WAYBILL_FAILURE',
  GET_BOOKING_ADMIN_START: 'GET_BOOKING_ADMIN_START',

  UPDATE_COMPLETE_START: 'UPDATE_COMPLETE_START',
  UPDATE_COMPLETE_MULTIPLE_START: 'UPDATE_COMPLETE_MULTIPLE_START',
  UPDATE_COMPLETE_FAILURE: 'UPDATE_COMPLETE_FAILURE',
  UPDATE_COMPLETE_SUCCESS: 'UPDATE_COMPLETE_SUCCESS',

  UPDATE_CONTENT_B_START: 'UPDATE_CONTENT_B_START',
  UPDATE_CONTENT_B_SUCCESS: 'UPDATE_CONTENT_B_SUCCESS',
  UPDATE_CONTENT_B_FAILURE: 'UPDATE_CONTENT_B_FAILURE',

  GET_BOOKING_WAY_BILL_START: 'GET_BOOKING_WAY_BILL_START',
  GET_BOOKING_WAY_BILL_SUCCESS: 'GET_BOOKING_WAY_BILL_SUCCESS',
  GET_BOOKING_WAY_BILL_FAILURE: 'GET_BOOKING_WAY_BILL_FAILURE',
};

export default BOOKING_ACTION_TYPES;
