const USER_ACTIONS_TYPES = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
  SIGN_IN_START: 'SIGN_IN_START',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',

  UPDATE_ADDRESS_START: 'UPDATE_ADDRESS_START',
  UPDATE_PHONE_START: 'UPDATE_PHONE_START',

  UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
  AUTH_EXPIRED_TYPES: 'AUTH_EXPIRED_TYPES',

  // CHECK_SESSION_USER_START: 'CHECK_SESSION_USER_START',
  // CHECK_SESSION_USER_FAILURE: 'CHECK_SESSION_USER_FAILURE',
};

export default USER_ACTIONS_TYPES;
